### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by zjpjack** [farkhor/PaRMAT#3]
I use make in Release folder, but it has the following errors:

g++ -O3 -Wall -c -fmessage-length=0 -pthread -std=c++0x -MMD -MP -MF"src/Edge.d" -MT"src/Edge.d" -o "src/Edge.o" "../src/Edge.cpp"
In file included from ../src/Edge.hpp:6:0,
                 from ../src/Edge.cpp:1:
../src/internal_config.hpp:9:7: error: expected nested-name-specifier before ‘EdgeIndexType’
../src/internal_config.hpp:9:7: error: ‘EdgeIndexType’ has not been declared
../src/internal_config.hpp:9:21: error: expected ‘;’ before ‘=’ token
../src/internal_config.hpp:9:21: error: expected unqualified-id before ‘=’ token
In file included from ../src/Edge.cpp:1:0:
../src/Edge.hpp:14:2: error: ‘EdgeIndexType’ does not name a type
../src/Edge.hpp:20:21: error: expected ‘)’ before ‘rec_src’
../src/Edge.cpp:4:11: error: expected constructor, destructor, or type conversion before ‘(’ token
../src/Edge.cpp: In copy constructor ‘Edge::Edge(const Edge&)’:
../src/Edge.cpp:9:2: error: ‘src’ was not declared in this scope
../src/Edge.cpp:9:16: error: ‘const class Edge’ has no member named ‘src’
../src/Edge.cpp:10:2: error: ‘dst’ was not declared in this scope
../src/Edge.cpp:10:16: error: ‘const class Edge’ has no member named ‘dst’
../src/Edge.cpp: In member function ‘Edge& Edge::operator=(const Edge&)’:
../src/Edge.cpp:14:2: error: ‘src’ was not declared in this scope
../src/Edge.cpp:14:16: error: ‘const class Edge’ has no member named ‘src’
../src/Edge.cpp:15:2: error: ‘dst’ was not declared in this scope
../src/Edge.cpp:15:16: error: ‘const class Edge’ has no member named ‘dst’
../src/Edge.cpp: In member function ‘bool Edge::selfEdge()’:
../src/Edge.cpp:20:11: error: ‘src’ was not declared in this scope
../src/Edge.cpp:20:18: error: ‘dst’ was not declared in this scope
../src/Edge.cpp: In function ‘bool operator<(const Edge&, const Edge&)’:
../src/Edge.cpp:24:10: error: ‘const class Edge’ has no member named ‘src’
../src/Edge.cpp:24:20: error: ‘const class Edge’ has no member named ‘src’
../src/Edge.cpp:26:15: error: ‘const class Edge’ has no member named ‘src’
../src/Edge.cpp:26:25: error: ‘const class Edge’ has no member named ‘src’
../src/Edge.cpp:28:15: error: ‘const class Edge’ has no member named ‘dst’
../src/Edge.cpp:28:25: error: ‘const class Edge’ has no member named ‘dst’
../src/Edge.cpp: In function ‘bool operator==(const Edge&, const Edge&)’:
../src/Edge.cpp:35:15: error: ‘const class Edge’ has no member named ‘dst’
../src/Edge.cpp:35:26: error: ‘const class Edge’ has no member named ‘dst’
../src/Edge.cpp:35:37: error: ‘const class Edge’ has no member named ‘src’
../src/Edge.cpp:35:48: error: ‘const class Edge’ has no member named ‘src’
../src/Edge.cpp: In function ‘std::ostream& operator<<(std::ostream&, Edge&)’:
../src/Edge.cpp:39:15: error: ‘class Edge’ has no member named ‘src’
../src/Edge.cpp:39:36: error: ‘class Edge’ has no member named ‘dst’
../src/Edge.cpp: In function ‘bool operator==(const Edge&, const Edge&)’:
../src/Edge.cpp:36:1: warning: control reaches end of non-void function [-Wreturn-type]
../src/Edge.cpp: In function ‘bool operator<(const Edge&, const Edge&)’:
../src/Edge.cpp:32:1: warning: control reaches end of non-void function [-Wreturn-type]
../src/Edge.cpp: In member function ‘bool Edge::selfEdge()’:
../src/Edge.cpp:21:1: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [src/Edge.o] Error 1

Thanks

**Comment by farkhor** [comment]
Can you please tell me if you are modifying the files? For example, in the existing Release make the C++11 compilation flag is indicated with `-std=c++11` however yours is `-std=c++0x` (not that it makes a difference).

**Comment by Narendramallela** [comment]
Hi, I also got the compilation error can you please look into this

/Users/Narendra/Downloads/PaRMAT-master/src/PaRMAT.cpp
/Users/Narendra/Downloads/PaRMAT-master/src/PaRMAT.cpp:88:25: Implicit conversion loses integer precision: 'unsigned long' to 'unsigned int'
/Users/Narendra/Downloads/PaRMAT-master/src/GraphGen_sorted.cpp
/Users/Narendra/Downloads/PaRMAT-master/src/GraphGen_sorted.cpp:92:25: Implicit conversion loses integer precision: 'size_type' (aka 'unsigned long') to 'unsigned int'
/Users/Narendra/Downloads/PaRMAT-master/src/GraphGen_sorted.cpp:100:25: Implicit conversion loses integer precision: 'size_type' (aka 'unsigned long') to 'unsigned int'
/Users/Narendra/Downloads/PaRMAT-master/src/GraphGen_notSorted.cpp
/Users/Narendra/Downloads/PaRMAT-master/src/GraphGen_notSorted.cpp:81:6: Code will never be executed
/Users/Narendra/Downloads/PaRMAT-master/src/utils.cpp
/Users/Narendra/Downloads/PaRMAT-master/src/utils.cpp:65:13: Implicit conversion loses integer precision: 'time_t' (aka 'long') to 'unsigned int'
/Users/Narendra/Downloads/PaRMAT-master/src/utils.cpp:159:30: Implicit conversion loses integer precision: 'unsigned long long' to 'EdgeIndexType' (aka 'unsigned int')
/Users/Narendra/Downloads/PaRMAT-master/src/utils.cpp:161:51: Implicit conversion loses integer precision: 'unsigned long long' to 'EdgeIndexType' (aka 'unsigned int')
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zjpjack** [comment]
@farkhor Yes, you are right! I use c++11 now, and it can successfully compile! Thanks!

**Comment by Narendramallela** [comment]
Hi zipjack,

Can you please guide me how to use this in mac . please help me

Thanks,
Narendra
