### ISSUE TITLE
Meaning of "unirected"

### ISSUE THREAD

**Issue by PJK** [farkhor/PaRMAT#7]
Hi @farkhor ,

Is it correct that the `-undirected` flag has an effect only when `-noDuplicateEdges` was also used, in which case it prevents generating both `x y` and `y x` edges?

Thanks!

**Comment by farkhor** [comment]
Hi @PJK,

No these two flags work independent of each other. `-undirected` constructs the specified graph only for the upper triangle of the adjacency matrix. `-noDuplicateEdges` disallows any probable repetition of one edge instance. For example, if `-noDuplicateEdges` is not enabled, an `x y` edge might appear multiple times in the output edge-list while with `-noDuplicateEdges` it is guaranteed that the instance (if appeared) is unique.

Cheers!

**Comment by PJK** [comment]
Ah, that makes sense. Thanks for clarifying!

**Comment by TarekAS** [comment]
To generate the lower triangle in an undirected graph, just run this command:

```
awk ' { t = $1; $1 = $2; $2 = t; print; } ' mygraph >> mygraph 
```
This will break the sorting if you generated it as sorted, so sort again using:

```
sort -k1,1n -k2,2n <mygraph > mysortedgraph
```

Wish this was a parameter though
